declare module "recharts" {
    export const BarChart: any
    export const Bar: any
    export const PieChart: any
    export const Pie: any
    export const RadarChart: any
    export const Radar: any
    export const PolarGrid: any
    export const PolarAngleAxis: any
    export const PolarRadiusAxis: any
    export const RadialBarChart: any
    export const RadialBar: any
    export const Tooltip: any
    export const Legend: any
    export const Area: any
    export const AreaChart: any
    export const LineChart: any
    export const Line: any
    export const XAxis: any
    export const YAxis: any
    export const CartesianGrid: any
    export const ResponsiveContainer: any
}
